[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3"
hex = "0.4"
methods = { path = "../methods" }
risc0-groth16 = { path = "../groth16" }
risc0-zkvm = { path = "../../../risc0/zkvm", features =["prove"] }
serde_json = "1.0"

