[package]
name = "halo2-extra"
version = "0.1.0"
edition = "2021"

[workspace]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
halo2_proofs ={git = "https://github.com/privacy-scaling-explorations/halo2.git" }
ff = "0.13"
halo2curves = { version = "0.1.0" }
rand_core = "0.6.4"
assert_matches = "1.5"
bincode = "1.3.3"
halo2-core = {path = "../core"}
rmp-serde = "1.1.2"
